### ISSUE TITLE
Tab compression

### ISSUE THREAD

**Issue by jtagcat** [numirias/paxmod#46]
![image](https://user-images.githubusercontent.com/38327267/70063639-093be800-15e0-11ea-9ae3-f1c1b9b19323.png)
I'd expect a new row to be made, when normally firefox would display the tab scrolling arrow, currently all tabs could be fit on one row.
1) Make the tabs smaller until a set minimum of a tab's width (compression)
![Screenshot from 2019-12-03 17-28-19](https://user-images.githubusercontent.com/38327267/70064665-d0047780-15e1-11ea-80df-ef197f38c6ba.png)
1) When firefox normally shows you the tab scrolling arrows, then go to a new row instead.
![Screenshot from 2019-12-03 17-28-33](https://user-images.githubusercontent.com/38327267/70064765-f7f3db00-15e1-11ea-801e-25ca9ca10f5f.png)
1) illustrating expected behaviour:
![image](https://user-images.githubusercontent.com/38327267/70066518-c4668000-15e4-11ea-8c85-44d2ea53e56d.png)

Related: #44 (but essentially the opposite of this issue)

**Comment by Delta2401** [comment]
I have noticed a way to shrink my tabs to the size they were before. After about a week, I realized it simply didn't rename the tabs to a shorter version, or any cutoff anymore; as the bug. Which is why when I restore some sessions, at least for a brief moment, it can all be small; or default view, something loads that changes the tab sizes due to the name.

This led to my downloading of my Tab Mix - Rename Tab extension, to rename all the tabs to shorter, succinct tab titles. Sure enough, I got them all smaller, for all rows. More or less the amount of tab rows I had several weeks back; the only downside is they aren't in uniform sizes, where you can plot your close tab X, when closing multiple tabs. I use the Tab Mix - Rename Tab, because you can lock the tab of yours to that tab no matter URL, etc. So for the tabs I keep open and almost never change, they will be there.

Right now, I am happy enough with this effect; as it is more or less, almost as functional in multirow tabs as before.

A way to fix this extension, I think would be to create an extension that renames all tabs to the proper amount of spaces you put in/ cropping off the extra; to make a more uniformed tab size. Or just not care about specific tab sizes, and just not have extra spaces; idk - depends on preference.

**Comment by jtagcat** [comment]
Renaming is not dynamic (unless you really want to make it) - all tabs are always the same size, what is still the same bad for me.
Also by renaming, you can't hover on the tab to get it's full name.

**Comment by Delta2401** [comment]
Well, between not having dynamic tabs, and being able to hover for full name, and having 50 rows of tabs for no reason; I think it's still the best option so far; I hope we get a fix. Also, if you use a good name shortening convention, you should be able to not need a full name hover, no?

**Comment by numirias** [comment]
I'm assuming the tab shrinking issue relates to #47 which is now fixed. If not, feel free to reopen.

**Comment by jtagcat** [comment]
Referring to the settings of the extension:
Max. tab width has been indeed fixed. (you can now set tab size for tabs statically (not dynamically).
Min. tab width (what I'm the most after) is still broken. (tabs are pretty much always the same size currently)
As such, I'd reopen this issue, but for some reason (probably GH Repository settings prevent me), I can't. @numirias

**Comment by numirias** [comment]
@jtagcat The settings work for me. You might be misunderstanding the tab resizing logic: A tab takes *Default tab width* percent of the space in a row, but at least *Min. tab width* pixels, and at most *Max. tab width* pixels.

If you set *default* to 0%, your tabs will each take *max* pixels and shrink to *min* pixels, before a new line is created. Or in other words, *default: 10%* means you want 10 tabs per row, 0% means you allow an infinite amount of tabs per row within the bounds of *min* and *max*.

**Comment by jtagcat** [comment]
Makes more sense now..
..but it should be clarified somehow.
